import React from 'react';
import './globals.css'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import DrawerMenu from '@/Components/Drawer/DrawerMenu';
import LayOutAppBar from '@/Components/Drawer/AppBar';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: 'flex' }}>
          <CssBaseline />
          <LayOutAppBar />
          <DrawerMenu />
          <Box component="main" sx={{ flexGrow: 1, p: 0 }}>
            {children}
          </Box>
        </Box>
      </body>
    </html>
  )
}
